family: ${ECS_WORKER_TASK}
networkMode: awsvpc
cpu: "${ECS_CPU_UNITS}"
memory: "${ECS_MEMORY_UNITS}"
executionRoleArn: ${ROLE_ARN}
taskRoleArn: ${ROLE_ARN}
requiresCompatibilities:
  - FARGATE
containerDefinitions:
  - name: logs
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
    firelensConfiguration:
      type: fluentbit
    memoryReservation: 50
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: /analysistools/${TIER}/${APP}/worker
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: logs

  - name: backend
    image: ${BACKEND_IMAGE_LATEST}
    environment:
      - name: FLASK_ENV
        value: production
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: WORKER_MODE
        value: "true"
    logConfiguration:
      logDriver: awsfirelens
      options:
        Name: datadog
        tls: "on"
        tls.verify: "off"
        dd_service: ${TIER}-${APP}-worker
        dd_source: python
        dd_tags: project:${APP} tier:${TIER}
        provider: ecs
      secretOptions:
        - name: Host
          valueFrom: /analysistools/${TIER}/datadog/log_endpoint_host
        - name: apikey
          valueFrom: /analysistools/${TIER}/datadog/api_key
    mountPoints:
      - sourceVolume: efs-storage
        containerPath: /deploy/app/tmp
        readOnly: false
    memoryReservation: 1024

volumes:
  - name: efs-storage
    efsVolumeConfiguration:
      fileSystemId: ${EFS_FILESYSTEM_ID}
      transitEncryption: ENABLED
      authorizationConfig:
        accessPointId: ${EFS_ACCESS_POINT_ID}
        iam: ENABLED

tags:
  - key: Project
    value: ${APP}
  - key: ApplicationName
    value: ${APP}
  - key: ResourceName
    value: ${TIER}-${APP}-worker-ecs-task
  - key: ResourceFunction
    value: compute
  - key: EnvironmentTier
    value: ${ENVIRONMENT_TIER}
  - key: Creator
    value: GitHub-Actions
