services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "80:80"
    volumes:
      - ../tmp:/deploy/app/tmp
    environment:
      - PYTHONUNBUFFERED=1
